global:
  scrape_interval: 1m
  evaluation_interval: 1m
  scrape_timeout: 10s
  external_labels:
    customer: neonism

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
          - "172.18.79.2:9100"
          - "172.18.79.33:9100"
          - "172.18.79.1:9100"
          - "172.18.79.17:9100"
          - "172.18.79.18:9100"
          - "172.18.79.19:9100"
remote_write:
  - url: http://victoria-metrics:8428/api/v1/write