global:
  scrape_interval: 1m
  evaluation_interval: 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
          - "172.18.100.18:9182"
          - "172.18.100.5:9182"
          - "172.18.100.8:9182"
          - "172.20.100.18:9182"
